# Site settings
title: Jonathan Laster
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Software & Automotive technologist. Addicted to the internet.
baseurl: "/jonathan-laster" # the subpath of your site, e.g. /blog/
url: "http://laster.co" # the base hostname & protocol for your site
twitter_username: whoislaster
github_username:  goodkaws

# Build settings
markdown: kramdown
